package no.nav.dagpenger.iverksett.kontrakter.felles

enum class SvarId {

    // Felles
    JA,
    NEI,

    // Forutgående medlemskap
    MEDLEM_MER_ENN_5_ÅR_AVBRUDD_MINDRE_ENN_10_ÅR,
    MEDLEM_MER_ENN_7_ÅR_AVBRUDD_MER_ENN_10ÅR,
    I_LANDET_FOR_GJENFORENING_ELLER_GIFTE_SEG,
    ANDRE_FORELDER_MEDLEM_SISTE_5_ÅR,
    ANDRE_FORELDER_MEDLEM_MINST_5_ÅR_AVBRUDD_MINDRE_ENN_10_ÅR,
    ANDRE_FORELDER_MEDLEM_MINST_7_ÅR_AVBRUDD_MER_ENN_10_ÅR,
    TOTALVURDERING_OPPFYLLER_FORSKRIFT,
    MEDLEM_MER_ENN_5_ÅR_EØS,

    // Opphold
    ARBEID_NORSK_ARBEIDSGIVER,
    UTENLANDSOPPHOLD_MINDRE_ENN_6_UKER,

     // Aktivitet i arbeid
    ER_I_ARBEID,
    ETABLERER_EGEN_VIRKSOMHET,
    HAR_FORBIGÅENDE_SYKDOM,

}
